server:
  port: 8888
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: default
          uri: no://op
          predicates:
            - Path=/**
storage:
  path: .main/resources
feignClient:
  url: http://192.168.1.85:9090
#dns:
#  gateway:
#    ip: 192.168.7.30

