server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: default
          uri: no://op
          predicates:
            - Path=/**
storage:
  path: ../storage
feign:
  client:
    config:
      default:
        url: ${remote.route.service.url:http://192.168.1.85:9090}

